### PR TITLE
Change chrome icons

### PR DESCRIPTION
**Pull request by parnissolle**
I prefer the old octocat icons for github-gmail

### CODE REVIEW

**Comment by muan** [comment]
Since this is not an official GitHub extension, we can not use octocat as the logo.

**Comment by parnissolle** [comment]
Oh, okay I see ;)
And for the other things like i18n ?

**Comment by muan** [comment]
Ah those seem good, sorry I didn't read the files changed given the description. If you can open another PR for i18n bits that'd be great! :bow:

**Comment by parnissolle** [comment]
I was AFK for a while, sorry!
I'll do that ASAP ;)

**Pull request closed without merging**
