### PR TITLE
first crack at adding a quick unwatch repo button

### PR DESCRIPTION
**Pull request by kevinhughes27**
I get automatically subscribed to new repos a lot from work and I usually just unwatch them unless its close to an area I'm working on. Yesterday I played around with adding another button which is a one click unwatch without leaving my gmail inbox.

@muan what do you think - is this something you would consider incorporating into the extension? Let me know if you think so and I'll put some more work into cleaning it up a bit. :rocket:

### CODE REVIEW

**Comment by y1970** [comment]
iam sorrymy friend buy i am beginner to the tor use,i dont know how to set nodes ,fingerprints and generally where to find a manual to understand theuse of this terms

Sent from Yahoo Mail on Android

**Comment by kevinhughes27** [comment]
uh what just happened here lol

**Comment by muan** [comment]
@kevinhughes27 thank you! :grin: This is definitely something that I'd tried adding, but failed, check out #23. However, executing JS on github.com this way seems bit too invasive to me. Have you tried using the `list-unsubscribe` url instead?

Meanwhile, checkout https://github.com/josh/list-unsubscribe and https://github.com/mastahyeti/OctoGAS#mute :grin: I use OctoGAS.

**Comment by kevinhughes27** [comment]
it is a bit invasive - I guess thats where the open sourceness kicks in. Maybe I'll see about solving it with list unsubscribe.

**Comment by kevinhughes27** [comment]
played around with following the unsubscribe link - it works but I couldn't find a good way to ensure the tab was loaded before closing it. Its currently using a setTimeout which is totally not ideal.

**Comment by muan** [comment]
Oops missed your edit.

Um I'd like to take a look at the issue but don't have the time recently. Let's leave this open here for now and I'll circle back. :)

**Comment by kevinhughes27** [comment]
me neither! sounds good to me

**Comment by jjasghar** [comment]
I'd love to see this merged, gonna watch this PR :metal:

**Comment by catchkley** [comment]
M

**Comment by muan** [comment]
Hi y'all, with GitHub's newly added unsubscribe link, I was able to add a mute button with an in-page request (customizable shortcut default to `shift + h`), check it out in `0.7.0` :sparkles:.

**Pull request closed without merging**
